In [10]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\22013361\appdata\local\anaconda3\envs\c338\lib\site-packages (3.1.4)
Requirement already satisfied: et-xmlfile in c:\users\22013361\appdata\local\anaconda3\envs\c338\lib\site-packages (from openpyxl) (1.1.0)

In [11]:
import pandas as pd

In [24]:
df = pd.read_excel("Student Survey.xlsx")
df

,Timestamp,What is your gender?,How old are you this year?,Which tertiary education institution are you in?,Of what ethnicity are you,Of what religion are you?,Do your parents work?,How many siblings do you have,What type of housing do you live in?,"What is your current cGPA? Please answer in 2 decimal points(e.g., 3.30)",...,How many hours per week do you dedicate to your CCA(s)?,"On a scale of 1 to 10, how satisfied are you with your overall school experience? (1 being very unsatisfied, 10 being very satisfied)",Which specific area of your school experience do you feel most satisfied with?,Which specific area of your school experience are you not satisfied with?,"\nHow do you rate the support provided by your school in achieving your personal and academic goals? (1 being very poor, 10 being excellent)",Do you feel that your school fosters a sense of community and belonging among its students?,Do have your future career planned already?,Write down at least 3 career options after graduation (e.g. 1. teacher 2. chef 3. doctor),Write down if there is any 3 career option after graduation that you would be interested to do (e.g. 1. teacher 2. chef 3. doctor),"With the career options that you have stated, briefly give the skills that is required for the options.(e.g. 1. Patience 2. Cooking 3. Precision)"
0,2024/04/24 9:31:05 am GMT+8,Male,19,Polytechnic,Chinese,Christian,Mother Only,1,HDB,2.94,...,NaN,6,Courses,Lecturers,4,Yes,Planned,"Office Worker, Entrepreneur or Real Estate Agent",NaN,"Discipline, Patience and Integrity"
1,2024/04/24 9:33:21 am GMT+8,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,2024/04/24 9:35:09 am GMT+8,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,2024/04/24 9:36:28 am GMT+8,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,2024/04/24 9:36:55 am GMT+8,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.1,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,2024/06/03 8:43:33 am GMT+8,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,2024/06/03 9:33:05 am GMT+8,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.9,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,2024/06/03 10:04:10 am GMT+8,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.4,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,2024/06/03 10:49:04 am GMT+8,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,2024/06/04 3:07:07 am GMT+8,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [25]:
df = df.drop(columns = "Timestamp")

In [26]:
df = df.rename(columns = {'What is your gender?':'Gender', 'How old are you this year?' : 'Age','Which tertiary education institution are you in?':'Tertiary Education','Of what ethnicity are you':'Ethnicity','Of what religion are you?':'Religion','Do your parents work?':'Parents Work','How many siblings do you have':'Siblings','What type of housing do you live in?':'Housing','What is your current cGPA? Please answer  in 2 decimal points(e.g., 3.30)':'Current GPA','What is your desired cGPA?  Please answer  in 2 decimal points(e.g., 3.30)':'Desired GPA','On average, how many times are you absent for class in a semester':'Absences','Do you play video games?':'Video Games','How many Hours  do you game per week?':'Game Hours','What Game Genre Do You Mostly Play?':'Game Genre','Do You Play Games With Friends?':'Game With Friends','During what hours do you usually start playing video games? Please answer in the 24 hour time format (e.g., 0000, 1800, 2200 etc)':'Game Timing','Do your Parent(s) Stop You From Gaming?':'Gaming Stopped','What Is The Main Reason You Started Gaming':'Main Reason Started Gaming','Are you working as a part-timer as of right now?':'Part-Time','How Many Hours Do You Work A Week?':'Part-Time Hours','What Job Sector Do You Work In?':'Job Sector','Which Days Of The Week Do You Work?':'Days Of Week Worked','Do you participate in any Co-Curricular Activities (CCAs) at your school?':'CCAs Participated','How many Co-Curricular Activities (CCAs) are you currently participating in?':'No. Of CCAs Participated','Please specify the name(s) of the CCA(s) you are involved in.':'Names Of CCAs','What role do you hold in your CCA(s)? ':'CCA Role','How many hours per week do you dedicate to your CCA(s)? ':'CCA Hours','On a scale of 1 to 10, how satisfied are you with your overall school experience? (1 being very unsatisfied, 10 being very satisfied)':'School Satisfaction Level','Which specific area of your school experience do you feel most satisfied with?':'Satisfied Area','Which specific area of your school experience are you not satisfied with? ':'Unsatisfied Area','\nHow do you rate the support provided by your school in achieving your personal and academic goals? (1 being very poor, 10 being excellent)':'Support Level','Do you feel that your school fosters a sense of community and belonging among its students? ':'Sense Of Belonging','Do have your future career planned already?':'Future Planned','Write down at least 3 career options after graduation (e.g. 1. teacher 2. chef  3. doctor)':'3 career options after graduation','Write down if there is any 3 career option after graduation that you would be interested to do  (e.g. 1. teacher 2. chef  3. doctor)':'3 career option interested to do','With the career options that you have stated, briefly give the skills that is required for the options.(e.g. 1. Patience 2. Cooking 3. Precision)':'Skills Required'})
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
0,Male,19,Polytechnic,Chinese,Christian,Mother Only,1,HDB,2.94,4.5,...,NaN,6,Courses,Lecturers,4,Yes,Planned,"Office Worker, Entrepreneur or Real Estate Agent",NaN,"Discipline, Patience and Integrity"
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.5,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.3,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.1,4,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.6,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.9,3.5,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.4,3,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.5,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.7,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [27]:
df = df.loc[df['Tertiary Education'].str.contains('Polytechnic', case=False, na=False)]
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
0,Male,19,Polytechnic,Chinese,Christian,Mother Only,1,HDB,2.94,4.5,...,NaN,6,Courses,Lecturers,4,Yes,Planned,"Office Worker, Entrepreneur or Real Estate Agent",NaN,"Discipline, Patience and Integrity"
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.5,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.3,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.1,4,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.6,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.9,3.5,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.4,3,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.5,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.7,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [28]:
print(df.columns)

Index(['Gender', 'Age', 'Tertiary Education', 'Ethnicity', 'Religion',
       'Parents Work', 'Siblings', 'Housing', 'Current GPA', 'Desired GPA',
       'Absences', 'Video Games', 'Game Hours', 'Game Genre',
       'Game With Friends', 'Game Timing', 'Gaming Stopped',
       'Main Reason Started Gaming', 'Part-Time', 'Part-Time Hours',
       'Job Sector', 'Days Of Week Worked', 'CCAs Participated',
       'No. Of CCAs Participated',
       'Please specify the name(s) of the CCA(s) you are involved in. ',
       'CCA Role', 'CCA Hours', 'School Satisfaction Level', 'Satisfied Area',
       'Unsatisfied Area', 'Support Level', 'Sense Of Belonging',
       'Future Planned', '3 career options after graduation',
       '3 career option interested to do', 'Skills Required'],
      dtype='object')

In [29]:
df['Siblings'] = df['Siblings'].replace({'5 siblings': '5'})

# Print the unique values in the 'Siblings' column to verify the replacement
print(df.iloc[32])

Gender                                                                                   Male
Age                                                                                        17
Tertiary Education                                                                Polytechnic
Ethnicity                                                                             Chinese
Religion                                                                         Free thinker
Parents Work                                                                       Both Works
Siblings                                                           1 sibling 4 half siblings
Housing                                                                                   HDB
Current GPA                                                                               nil
Desired GPA                                                                               nil
Absences                                                                                    0
Video Games                                                                               Yes
Game Hours                                                                            20 - 29
Game Genre                                                           Action(FPS, Shooter etc)
Game With Friends                                                                         Yes
Game Timing                                                                              1800
Gaming Stopped                                                                             No
Main Reason Started Gaming                                                To make new friends
Part-Time                                                                                  No
Part-Time Hours                                                                           NaN
Job Sector                                                                                NaN
Days Of Week Worked                                                                       NaN
CCAs Participated                                                                         Yes
No. Of CCAs Participated                                                                    1
Please specify the name(s) of the CCA(s) you are involved in.                  dragon boating
CCA Role                                                                               Member
CCA Hours                                                                                 5.0
School Satisfaction Level                                                                  10
Satisfied Area                                                                    Social Life
Unsatisfied Area                                                                         None
Support Level                                                                               8
Sense Of Belonging                                                                        Yes
Future Planned                                                                        Planned
3 career options after graduation                                 boxer entrepreneur engineer
3 career option interested to do                                                          NaN
Skills Required                                                    discipline networking math
Name: 32, dtype: object

C:\Users\22013361\AppData\Local\Temp\ipykernel_8756\799589991.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Siblings'] = df['Siblings'].replace({'5 siblings': '5'})

In [30]:
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
0,Male,19,Polytechnic,Chinese,Christian,Mother Only,1,HDB,2.94,4.5,...,NaN,6,Courses,Lecturers,4,Yes,Planned,"Office Worker, Entrepreneur or Real Estate Agent",NaN,"Discipline, Patience and Integrity"
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.5,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.3,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.1,4,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.6,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.9,3.5,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.4,3,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.5,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.7,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [31]:
df['Current GPA'] = pd.to_numeric(df['Current GPA'], errors='coerce')

df = df.dropna(subset=['Current GPA'])
df

C:\Users\22013361\AppData\Local\Temp\ipykernel_8756\2806279195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Current GPA'] = pd.to_numeric(df['Current GPA'], errors='coerce')

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
0,Male,19,Polytechnic,Chinese,Christian,Mother Only,1,HDB,2.94,4.5,...,NaN,6,Courses,Lecturers,4,Yes,Planned,"Office Worker, Entrepreneur or Real Estate Agent",NaN,"Discipline, Patience and Integrity"
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.5,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.3,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.6,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.5,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.5,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.7,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [32]:
df['Desired GPA'] = pd.to_numeric(df['Desired GPA'], errors='coerce')

df = df.dropna(subset=['Desired GPA'])
df

C:\Users\22013361\AppData\Local\Temp\ipykernel_8756\2525657328.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Desired GPA'] = pd.to_numeric(df['Desired GPA'], errors='coerce')

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
0,Male,19,Polytechnic,Chinese,Christian,Mother Only,1,HDB,2.94,4.50,...,NaN,6,Courses,Lecturers,4,Yes,Planned,"Office Worker, Entrepreneur or Real Estate Agent",NaN,"Discipline, Patience and Integrity"
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [33]:
df = df[(df['Current GPA'] >= 0) & (df['Current GPA'] <= 4)]
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
0,Male,19,Polytechnic,Chinese,Christian,Mother Only,1,HDB,2.94,4.50,...,NaN,6,Courses,Lecturers,4,Yes,Planned,"Office Worker, Entrepreneur or Real Estate Agent",NaN,"Discipline, Patience and Integrity"
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [34]:
df = df[(df['Desired GPA'] >= 0) & (df['Desired GPA'] <= 4)]
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
5,Male,19,Polytechnic,Chinese,skin walker,Mother Only,1,HDB,1.96,2.80,...,NaN,6,Social Life,None,6,Yes,Undecided,NaN,nop,nop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [35]:
df.columns

Index(['Gender', 'Age', 'Tertiary Education', 'Ethnicity', 'Religion',
       'Parents Work', 'Siblings', 'Housing', 'Current GPA', 'Desired GPA',
       'Absences', 'Video Games', 'Game Hours', 'Game Genre',
       'Game With Friends', 'Game Timing', 'Gaming Stopped',
       'Main Reason Started Gaming', 'Part-Time', 'Part-Time Hours',
       'Job Sector', 'Days Of Week Worked', 'CCAs Participated',
       'No. Of CCAs Participated',
       'Please specify the name(s) of the CCA(s) you are involved in. ',
       'CCA Role', 'CCA Hours', 'School Satisfaction Level', 'Satisfied Area',
       'Unsatisfied Area', 'Support Level', 'Sense Of Belonging',
       'Future Planned', '3 career options after graduation',
       '3 career option interested to do', 'Skills Required'],
      dtype='object')

In [36]:
df['Absences'] = pd.to_numeric(df['Absences'], errors='coerce')

df = df.dropna(subset=['Absences'])
df

C:\Users\22013361\AppData\Local\Temp\ipykernel_8756\4142474246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Absences'] = pd.to_numeric(df['Absences'], errors='coerce')

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
5,Male,19,Polytechnic,Chinese,skin walker,Mother Only,1,HDB,1.96,2.80,...,NaN,6,Social Life,None,6,Yes,Undecided,NaN,nop,nop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [50]:
columns_to_replace = ['Game Hours', 'Game Genre',
       'Game With Friends', 'Game Timing', 'Gaming Stopped',
       'Main Reason Started Gaming']
df[columns_to_replace] = df[columns_to_replace].replace(['NaN', None], "Don't Play Video Games")
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
5,Male,19,Polytechnic,Chinese,skin walker,Mother Only,1,HDB,1.96,2.80,...,NaN,6,Social Life,None,6,Yes,Undecided,NaN,nop,nop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [51]:
print(df['Game Hours'])

1                     30 - 39
2      Don't Play Video Games
3                     20 - 29
4                        > 84
5         2019-10-01 00:00:00
                ...
255    Don't Play Video Games
256                   40 - 49
257                       < 9
258    Don't Play Video Games
259    Don't Play Video Games
Name: Game Hours, Length: 202, dtype: object

In [52]:
columns_to_replace = ['Part-Time Hours',
       'Job Sector', 'Days Of Week Worked',]
df[columns_to_replace] = df[columns_to_replace].replace(['NaN', None], "Don't Work")
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
5,Male,19,Polytechnic,Chinese,skin walker,Mother Only,1,HDB,1.96,2.80,...,NaN,6,Social Life,None,6,Yes,Undecided,NaN,nop,nop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [53]:
print(df['Part-Time Hours'])

1               Don't Work
2      2015-11-01 00:00:00
3               Don't Work
4                     > 35
5               Don't Work
              ...
255             Don't Work
256             Don't Work
257             Don't Work
258    2015-11-01 00:00:00
259             Don't Work
Name: Part-Time Hours, Length: 202, dtype: object

In [64]:
df = df.rename(columns={'Please specify the name(s) of the CCA(s) you are involved in. ': 'CCA Names'})

In [65]:
df.columns

Index(['Gender', 'Age', 'Tertiary Education', 'Ethnicity', 'Religion',
       'Parents Work', 'Siblings', 'Housing', 'Current GPA', 'Desired GPA',
       'Absences', 'Video Games', 'Game Hours', 'Game Genre',
       'Game With Friends', 'Game Timing', 'Gaming Stopped',
       'Main Reason Started Gaming', 'Part-Time', 'Part-Time Hours',
       'Job Sector', 'Days Of Week Worked', 'CCAs Participated',
       'No. Of CCAs Participated', 'CCA Names', 'CCA Role', 'CCA Hours',
       'School Satisfaction Level', 'Satisfied Area', 'Unsatisfied Area',
       'Support Level', 'Sense Of Belonging', 'Future Planned',
       '3 career options after graduation', '3 career option interested to do',
       'Skills Required'],
      dtype='object')

In [73]:
columns_to_replace = ['No. Of CCAs Participated', 'CCA Names', 'CCA Role', 'CCA Hours']
df[columns_to_replace] = df[columns_to_replace].replace([None], "Don't Have CCA")
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,NaN,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,NaN,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,NaN,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,NaN,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
5,Male,19,Polytechnic,Chinese,skin walker,Mother Only,1,HDB,1.96,2.80,...,NaN,6,Social Life,None,6,Yes,Undecided,NaN,nop,nop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,NaN,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [88]:
df['CCA Hours'] = df['CCA Hours'].fillna("Don't Have CCA")
df

,Gender,Age,Tertiary Education,Ethnicity,Religion,Parents Work,Siblings,Housing,Current GPA,Desired GPA,...,CCA Hours,School Satisfaction Level,Satisfied Area,Unsatisfied Area,Support Level,Sense Of Belonging,Future Planned,3 career options after graduation,3 career option interested to do,Skills Required
1,Male,19,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,2.71,2.86,...,Don't Have CCA,5,Study Life,Results,7,No,Not yet,NaN,1. Software developer 2. Ai analyst 3. Cyberse...,1. Code 2. Detailed 3. Adaptable
2,Male,21,Polytechnic,Chinese,Buddhist,Both Works,2,HDB,0.98,1.50,...,Don't Have CCA,8,None,Results,7,Yes,Not yet,NaN,1,1
3,Male,19,Polytechnic,Chinese,Buddhist,Father Only,2,Condominium,2.86,3.30,...,Don't Have CCA,3,None,Results,4,Yes,Not yet,NaN,1. Entrepreneur 2. Food Reviewer 3. Food vlogger,1. Innovative 2. Critical 3. Entertaining
4,Male,22,Polytechnic,Chinese,Catholic,Both Works,2,Bungalow,3.10,4.00,...,Don't Have CCA,5,Social Life,Lecturers,7,No,Undecided,NaN,Not sure,Detailds
5,Male,19,Polytechnic,Chinese,skin walker,Mother Only,1,HDB,1.96,2.80,...,Don't Have CCA,6,Social Life,None,6,Yes,Undecided,NaN,nop,nop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Female,19,Polytechnic,Indian,Islam,Both Works,2,HDB,3.45,3.60,...,4.0,5,None,Results,5,Yes,Not yet,NaN,"Teacher, hospital Lab, pharmacist","Precision, laboratory skills, timeliness"
256,Male,19,Polytechnic,Chinese,Buddhist,Mother Only,2,HDB,2.90,3.50,...,Don't Have CCA,8,Study Life,Results,6,No,Undecided,NaN,1. Translator 2. Reporter 3. Sports Commentator,1. Language 2. Outspoken 3. Confidence
257,Female,19,Polytechnic,Chinese,Christian,Both Works,2,Condominium,2.40,3.00,...,5.0,8,Classmates,Results,7,Yes,Not yet,NaN,-,-
258,Female,24,Polytechnic,Chinese,Christian,Mother Only,4,HDB,1.81,2.50,...,3.0,8,Courses,Classmates,8,No,Planned,"nurse, journalist",NaN,"patience, writing skills, communication skills"
259,Female,20,Polytechnic,Malay,Islam,Father Only,1,Maisonnette,3.03,3.70,...,10.0,8,"Mixture of Studying, Social Life and Netball",Results,4,Yes,Undecided,NaN,NIL,NaN

In [92]:
print(df['CCA Hours'])

1      Don't Have CCA
2      Don't Have CCA
3      Don't Have CCA
4      Don't Have CCA
5      Don't Have CCA
            ...
255               4.0
256    Don't Have CCA
257               5.0
258               3.0
259              10.0
Name: CCA Hours, Length: 202, dtype: object

In [93]:
df.to_excel('cleansed_data.xlsx', index=False)